### ISSUE TITLE
How do i use with keyboard

### ISSUE THREAD

**Issue by leinxad** [Denhonator/KHPCSpeedrunTools#1]
Hi, thank you for this awesome tool, is useful even for not speedrunners, i play with keyboard and i havent been able to make the tool work. With the default keyboard qwerty config, what it should be the key combination used to trigger it?

**Comment by Denhonator** [comment]
It should work with equivalent keys on the keyboard. For save menu mod, default is shift, C, E, 3. For 2fm soft reset, it would be shift, C, E, R, 4. Let me know if that does not work

**Comment by leinxad** [comment]
None of the combinations worked

**Comment by Denhonator** [comment]
Did you verify that the program is running correctly? When you launch LuaBackend, what does it output?

**Comment by leinxad** [comment]
![image](https://user-images.githubusercontent.com/82228493/114227476-aa585280-993a-11eb-89a1-05837730b90a.png)
I alsto tested it with a controller and works, but with keyboard it doesnt.

**Comment by Denhonator** [comment]
Assuming you are talking about save menu mod, you are pressing left shift, c, e and 3 all at once while using default keybinds?

**Comment by leinxad** [comment]
yeah, i am talking about the save menu mod, and i pressed those keys at the same time.

**Comment by Denhonator** [comment]
Yes you are the only one, and it works for me on the keyboard.

After the line `local input = ReadInt(0x233D034-0x3A0606)` could you insert a new line that contains `print(input)` and tell me what the program outputs as you press those keys?

**Comment by Denhonator** [comment]
Oh, actually, maybe you don't have the newest version. Try download it again and see if it works

**Comment by leinxad** [comment]
1280
1280
1280
1280
1280
1280
1280
1024

**Comment by leinxad** [comment]
I downloaded the latest version a few hours ago to see if that would wix the problem but it didnt

**Comment by Denhonator** [comment]
> 1280
> 1280
> 1280
> 1280
> 1280
> 1280
> 1280
> 1024

That would imply only shift and c were pressed. On top of those, you must press the first person view button and the Gummi ship: show/hide score button (as shown in key configuration settings)

**Comment by leinxad** [comment]
That was the program output when i press the 4 keys together,
i press each key alone this is the output
1024
1024
1024
1024
1024

256
256
256
256

512
512
512
512

1
1
1

**Comment by leinxad** [comment]
oh my god, i rebinded those 4 buttons to 7,8,9,0 and then it worked, dont know why it doesnt with default binding

**Comment by Denhonator** [comment]
It might have something to do with your keyboard not handling multiple keys at once well
