### ISSUE TITLE
Gummi Skip mod just removes worlds.

### ISSUE THREAD

**Issue by Collatic** [Denhonator/KHPCSpeedrunTools#110]
I'm sure I downloaded everything right, but just in case I'm uploaded photos of my files.  Playing on epic games and I had the gummi skip mod before the update and it worked.  
P.S. Discord link is also expired. 

![glitch 1](https://github.com/user-attachments/assets/95e9d1dd-77ac-4ce5-87e6-09002d478ac7)
![glitch 2](https://github.com/user-attachments/assets/e0966787-9b68-49c1-8ff5-865fc9982b53)
![glitch 3](https://github.com/user-attachments/assets/309a936e-6e10-4b7a-8885-a473abce05d2)

**Comment by cahudson94** [comment]
I will look into this shortly, I am not really the maintainer for 2FM stuff as I just translate what Sonic does into a more uniform format so might take a bit. Thanks for the heads up on the link it will also get replaced with a non expiring one.

**Comment by cahudson94** [comment]
Never mind found what I messed up should be going up later today.
