### ISSUE TITLE
kh2 autosave doesn't work correctly

### ISSUE THREAD

**Issue by ryjx** [Denhonator/KHPCSpeedrunTools#127]
i have all my scripts and luabackend up to date, i have everything installed correctly (including the io_packages) and the script isn't working like it's supposed to. when i hold select on the load menu, the heart appears like it's supposed to, but it instead loads the save i was hovering over because the script doesn't make an autosave whenever i enter a room. i even checked the console with F2 and it's no longer saying "autosave created" like it did in the past.

**Comment by cahudson94** [comment]
Fix should be live in the next few hours when Denho merges the PR.

**Comment by ryjx** [comment]
> Contributor

i just updated all my scripts but it's still not creating autosaves. save anywhere doesn't work either. i'm on EGS.

**Comment by ryjx** [comment]
> > Contributor
> 
> i just updated all my scripts but it's still not creating autosaves. save anywhere doesn't work either. i'm on EGS.

nevermind, i just started a new playthrough and it does work! does it only work on new save files?

**Comment by cahudson94** [comment]
Not to my knowledge but I am also not the one to have written it just maintaining.

**Comment by Denhonator** [comment]
It should work off of any save, so the issue must've been something else
