### ISSUE TITLE
kh1 save anywhere doesn't run

### ISSUE THREAD

**Issue by elroyK** [Denhonator/KHPCSpeedrunTools#136]
Hi, I'm on EGS v1.0.0.10, I'm using the latest SaveAnywhere script but I get this error when I start the engine on LuaFrontend:

```
ERROR: .../Documents/LuaFrontend/scripts/kh1gl/1fmSaveAnywhere.lua:20: sol: no matching function call takes this number of arguments and the specified types
stack traceback:
[C]: in function 'base.ReadLong'
.../Documents/LuaFrontend/scripts/kh1gl/1fmSaveAnywhere.lua:20: in function 'base._OnInit'

ERROR: .../Documents/LuaFrontend/scripts/kh1gl/1fmSaveAnywhere.lua:48: sol: no matching function call takes this number of arguments and the specified types
stack traceback:
[C]: in function 'base.ReadByte'
.../Documents/LuaFrontend/scripts/kh1gl/1fmSaveAnywhere.lua:48: in function 'base._OnFrame'
```

Afaik this wasn't reported for kh1 but sorry if it was already
Thanks!

**Comment by cahudson94** [comment]
Couple of clarifying questions:

- Are you actually using Frontend as the screenshot infers?
- When and where did you get it if so?
- If it is a new install did you follow the configuration steps for it?

The error messaging you are seeing has less to do with the mod and is more likely a miss configuration issue or an outdated version of LuaFrontend.

**Comment by elroyK** [comment]
Hi :)

Nevermind I indeed failed to follow the proper config steps in LUA.md, thanks!
