### ISSUE TITLE
1FM Auto Attack breaks with B/O as confirm button.

### ISSUE THREAD

**Issue by Vladabdf** [Denhonator/KHPCSpeedrunTools#2]
Title.

**Comment by Denhonator** [comment]
Noted, will fix soon

**Comment by Vladabdf** [comment]
Any update on this? It's been a month and still broken.

**Comment by Denhonator** [comment]
Should be fixed now, sorry it took a while

**Comment by Vladabdf** [comment]
For consistency's sake, I would like to report this issue with KH2 as well.

**Comment by Denhonator** [comment]
I fixed this for KH2 now and made it only active in combat since there were some other issues with it as well
