### ISSUE TITLE
what is 1fmHookShip.lua ?

### ISSUE THREAD

**Issue by orbitchuuary44** [Denhonator/KHPCSpeedrunTools#27]
The description says Fixed hook ship mod for JP, please tell me more about what this files.

and, how do disable autosave for SaveAnywhere?

**Comment by Denhonator** [comment]
1fmHookShip.lua causes the ship to always appear when traveling to Neverland for the first time. I added this to the readme just now.

To disable the autosave, remove this part of the code:
`	if ReadFloat(soraHUD) == 1 and prevHUD < 1 then
		local f = io.open("autosave.dat", "wb")
		f:write(ReadString(continue, 0x16C00))
		f:close()
		ConsolePrint("Wrote autosave")
	end`

**Comment by orbitchuuary44** [comment]
Thanks for your quick reply.

I forgot to mention that there is a bug that probably occurs only in the Japanese version, so I'd like to report it.
When I do a soft reset of SaveAnywhere (1fm), the text in the dialogs and cutscenes is wrong (the text around the HUD is normal).
I can work around this bug by going back to the title from the save menu by pressing L1+L2+R2+Select, but this resets the resolution from 1440p to 1080p.

I'll be glad if you can fix this bug!
[https://i.imgur.com/1cH4sLw.png](url)
[https://i.imgur.com/vMGkiAz.png](url)

**Comment by Denhonator** [comment]
The soft reset function is very simple and identical between global and japanese version, so it is unknown to me what is causing that issue. Perhaps that bug is the reason Square made the title screen button hard reset the game.

**Comment by orbitchuuary44** [comment]
:_(
Thanks for reply :)
