### ISSUE TITLE
FasterAnims Hercules Time Trial Bug

### ISSUE THREAD

**Issue by sgern** [Denhonator/KHPCSpeedrunTools#3]
In the Hercules Cup time trial, if FasterAnims is running, then the timer will instantly drop to 0 as soon as the final round starts, making it impossible.

**Comment by Denhonator** [comment]
This probably got fixed in some update? This issue has not occurred to anyone for a long time by now that I know

**Comment by TheConfuZzledDude** [comment]
Hi, I think this same bug is happening (at least for me) in the Hades cup time trial, on like round 18 (One with the Defender and Large Bodies/Fat Bandits)
