### ISSUE TITLE
Enemy Rando not Rando.

### ISSUE THREAD

**Issue by Skeith-R** [Denhonator/KHPCSpeedrunTools#30]
[enemyrandolog.txt](https://github.com/Denhonator/KHPCSpeedrunTools/files/8923325/enemyrandolog.txt)

I can't seem to get enemy rando to work, all the other lua files seem to work, (Item and magic all seems random, I haven't gone far enough in the game to check rewards or levels. Got as far was wonderland and did not see any randomization of enemies. I don't know if I am doing anything wrong here but any help would be appreciated. Thanks!

**Comment by Denhonator** [comment]
Only select enemies are randomized. Many enemies can't be randomized due to crashing.
