### ISSUE TITLE
Packaging scripts as OpenKH mods

### ISSUE THREAD

**Issue by paulblessing** [Denhonator/KHPCSpeedrunTools#31]
LuaBackend Hook 1.6 allows for OpenKH mods to include Lua scripts so that they can be auto-updated and turned on/off easily in OpenKH Mods Manager. It'd be great if we could offer some of the scripts in this repo as OpenKH mods. That said, I can understand how maintaining separate repositories for each Lua script might not be something you're interested in, so I'd be willing to manage that if permission was given to do so. Credit would of course be given prominently in the GitHub repository as well as in the mod's `originalAuthor` tag.

**Comment by Denhonator** [comment]
If it doesn't require action from me, I don't mind

**Comment by paulblessing** [comment]
https://github.com/KH2FM-Mods-equations19/auto-save created for auto-save. May create additional ones for the others over time. Appreciate the permission.
