### ISSUE TITLE
Constant crashing in KH1

### ISSUE THREAD

**Issue by NezomiFloof** [Denhonator/KHPCSpeedrunTools#64]
I've tried LuaBackend, I've tried LuaFrontend, the only consistent thing that crashes are these scripts for KH1. I don't know if they got broken from the update but I'm on the Steam version. Nothing works.

**Comment by cahudson94** [comment]
Which scripts in particular? Only a handful of them have been updated as of yet.

**Comment by NezomiFloof** [comment]
Can confirm - only the updated scripts don't work. Currently KH1 rando has no workaround, as the script for RandoSomeLogic has yet to be updated, same goes for every script I'd consider useful aside from SaveAnywhere. Unfortunate

**Comment by cahudson94** [comment]
Rando has not been the priority, Denho is the primary maintainer for those scripts. I have picked up a lot of it but those are on the back burner especially given how much testing they will need. The 4k patch and Steam release broke literally everything, you will also need the updated version of LuaBackend or to change config on LuaFrontend for the updated scripts to work. If you want to be kept more up to date on where things stand the runners discord is where most of the discussion around this repo happens.

**Comment by NezomiFloof** [comment]
Well damn. Sucks that rando will be broken for a while. Can you link me to this discord server you're mentioning?

**Comment by cahudson94** [comment]
https://discord.gg/BYtRzqdC

**Comment by cahudson94** [comment]
Resolved
