### ISSUE TITLE
1fmAutoAttack.lua does not work on Steam release

### ISSUE THREAD

**Issue by Vladabdf** [Denhonator/KHPCSpeedrunTools#76]
I have not tested the updated EGS release, but as title suggests, I can confirm the script does not work on Steam, regardless of the input button selected

Edit: Just tested 2fmAutoAttack and it also does not work in KH2.

**Comment by cahudson94** [comment]
For 1fm, did you copy/create the op_packages folder and include the version file from inside?

**Comment by cahudson94** [comment]
This will not get any addressing if you do not give me further info in regards to 1FM.
