### ISSUE TITLE
KH2 Gummi Skips not working

### ISSUE THREAD

**Issue by VoltrixYT** [Denhonator/KHPCSpeedrunTools#78]
Honestly just waiting for this to be fixed...this is my main reason for playing kh2 is to skip the gummi missions if there is any other workaround lemme know thanks :)

**Comment by cahudson94** [comment]
There is an updated version of this mod available on the speedrunning discord, sadly no one from the 2 speed run or randomizer communities has really taken ownership of updating this repo.

**Comment by VoltrixYT** [comment]
Any chance you can link me to the discord or the updated mod? i'm struggling to find it apologies.

**Comment by cahudson94** [comment]
link to the discord is at the bottom of the main readme

**Comment by cahudson94** [comment]
Updated
