### ISSUE TITLE
Unlock 0 volume for 2FM?

### ISSUE THREAD

**Issue by tryashtar** [Denhonator/KHPCSpeedrunTools#8]
Hey there, I noticed the `1fmUnlock0Volume` script, that seems really helpful for recording specific sounds without stuff interfering. I was wondering, is there any chance of seeing a similar script for 2FM? I would really appreciate it if so! 🙏

I would try to make one myself, but I have no idea how you're able to figure out the addresses like `0x14E5DB`. If nothing else, I'd love to get some advice on that. Thanks much!!

**Comment by Denhonator** [comment]
It would be a little too complicated to try to explain how to do that, but I'll try to get around to doing that some time
