### ISSUE TITLE
[Linux/Steam Deck] Steam KH 1 rando not working at all on latest update

### ISSUE THREAD

**Issue by XandridFire** [Denhonator/KHPCSpeedrunTools#83]
On LuaFrontend it says `.../Downloads/LuaFrontend/scripts/kh1/1fmRandoSomeLogic.lua:2619: 'end' expected (to close 'function' at line 83) near <eof>` and says something very similar on each script. I've tried Luabackend, but the console doesn't appear as if there were no scripts. 

The prior update (before #82) the scripts kind of worked, I'm not sure if it's because of LuaFront/Backend, the scripts, or just the Steam version. But everything would work fine, until I go to Olympic Colosseum, the beginning cutscene plays a little then the game crashes. If I go to Traverse Town or Neverland, I can proceed fine until I noticed I can't activate a save point, nor open the pause menu, and only the "Attack" command is unlocked (no items or anything only dashes (-) on the command menu.

**Comment by XandridFire** [comment]
That did fix it, but I still am having this problem 
> The scripts kind of worked, I'm not sure if it's because of LuaFront/Backend, the scripts, or just the Steam version. But everything would work fine, until I go to Olympic Colosseum, the beginning cutscene plays a little then the game crashes. If I go to Traverse Town or Neverland, I can proceed fine until I noticed I can't activate a save point, nor open the pause menu, and only the "Attack" command is unlocked (no items or anything only dashes (-) on the command menu.

If it is a Luabackend problem, I'll just make an issue there

**Comment by cahudson94** [comment]
Luabackend would not have anything to do really with in game specifics, so no. I will have to do some testing to check that out.

**Comment by XandridFire** [comment]
I'm only using someone the mods that come from KHPCSpeedrunTools (SaveAnywhere, Rando, Instantgummi, Hookship, fasterdialog, fast camera, and earlyskip) and they're all updated (#84). I'm using Luabackend 1.8.0 and there weren't any extra steps to replicate them. I can see if I can upload a video or something of it happening.

**Comment by XandridFire** [comment]
This is the OC Crash: https://streamable.com/5ycv97

This is the no save access, only attack, no pause: https://streamable.com/zktu0k

**Comment by cahudson94** [comment]
For clarity is that just rando some logic?

With a mirror of your same setup I am not getting either of those errors. Do a one by one check on the files you have? Are you sure you have all of the correct rando files/folders? Some captures of what files/folders you have might help.

**Comment by XandridFire** [comment]
I've tried it without Randosomelogic, it's the same results. 
![Screenshot_20240805_211645](https://github.com/user-attachments/assets/cd267caa-f3a5-4294-a0de-854906bea433)
![Screenshot_20240805_211558](https://github.com/user-attachments/assets/3f179603-76cc-4952-b966-0ae8a818aabe)
![Screenshot_20240805_211533](https://github.com/user-attachments/assets/1eed9385-73a8-4bb9-a445-20a5a2507a9f)

**Comment by cahudson94** [comment]
Interestingly your file sizes differ, might be just how the systems handle compression but definitely something to look at. Also is there any chance of duplicate files in another location? What does your .toml look like?

**Comment by XandridFire** [comment]
![Screenshot_20240805_213111](https://github.com/user-attachments/assets/56d26e32-7146-41e6-b0a2-868eb8234bba)

**Comment by cahudson94** [comment]
There is a single line issue in early skip which I just PRed but that SHOULD not be throwing that many problems in.

**Comment by XandridFire** [comment]
Yea

**Comment by cahudson94** [comment]
We should move this discussion to dms on there, user name?

**Comment by XandridFire** [comment]
TripleO

**Comment by cahudson94** [comment]
Updating just for posterity, it is now noted and known that the Linux/Wine/Steam Deck versions of the game do handle some things differently so partial logic is working but needs to be investigated for root cause/solution.

**Comment by cahudson94** [comment]
Updated in PR should fix all noted issues here.
