### ISSUE TITLE
1fmEnemyRando Error

### ISSUE THREAD

**Issue by luckytime103** [Denhonator/KHPCSpeedrunTools#90]
Hi, i tried Enemy Randomization on Steam version and it seemed to work until a point where no enemy would randomize anymore, even those which used to work properly.

Now after trying a new seed, it doesn't work at all and it shows this error :

```
ERROR: ...OM HEARTS HD 1.5+2.5 ReMIX\scripts/kh1/1fmEnemyRando.lua:45: attempt to get length of a nil value (local 't')
stack traceback:
        ...OM HEARTS HD 1.5+2.5 ReMIX\scripts/kh1/1fmEnemyRando.lua:45: in upvalue 'PickRandom'
        ...OM HEARTS HD 1.5+2.5 ReMIX\scripts/kh1/1fmEnemyRando.lua:120: in upvalue 'AddAddrs'
        ...OM HEARTS HD 1.5+2.5 ReMIX\scripts/kh1/1fmEnemyRando.lua:215: in function 'base._OnInit'
```
I checked the script, and it seems that there is no adress for "parasite" in enemyTables, i don't know if it's the reason, i'm kinda confused
`120 	addrs[12][enemyAddresses[50]] = PickRandom(parasite) -- pc1`

**Comment by cahudson94** [comment]
correcting the missing entry thanks for the call out

**Comment by cahudson94** [comment]
Grab the new enemy tables file and see if that fixes things on your end?

**Comment by luckytime103** [comment]
yes it worked thanks
